spring:
  application:
    name: stock_auth_svc
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    auth:
      jdbc-url: jdbc:mysql://localhost:3306/${STOCK_AUTH_DB}
      username: ${STOCK_AUTH_USER}
      password: ${STOCK_AUTH_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    portfolio:
      jdbc-url: jdbc:mysql://localhost:3306/${STOCK_PORTFOLIO_DB}
      username: ${STOCK_PORTFOLIO_USER}
      password: ${STOCK_PORTFOLIO_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 900000 # 15 minutes in milliseconds
  refresh-token:
    expiration: 604800000 # 7 days in milliseconds

logging:
  level:
    com.sahil.stock.auth: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
